Added conditional compilation of the java code (depends on the existence of the javac compiler) and other applications (depend on the availability of the Web100 library).

diff --git a/branches/ndte/configure b/branches/ndte/configure
--- a/branches/ndte/configure
+++ b/branches/ndte/configure
@@ -695,6 +695,8 @@ AMDEPBACKSLASH
 CCDEPMODE
 am__fastdepCC_TRUE
 am__fastdepCC_FALSE
+HAVE_WEB100_TRUE
+HAVE_WEB100_FALSE
 LINKED_WEB100LIB
 INCLUDED_WEB100LIB
 LINKED_PCAPLIB
@@ -705,14 +707,17 @@ NDTLIBS
 NDTLIBDIR
 NDTINCDIR
 TOP_BUILD_DIRS
-GCJ
 NDTGCJFLAGS
 NDTJAR
 NDTJARFLAG
+GCJ
 GCJFLAGS
 GCJDEPMODE
 am__fastdepGCJ_TRUE
 am__fastdepGCJ_FALSE
+SGCJ
+HAVE_GCJ_TRUE
+HAVE_GCJ_FALSE
 CPP
 GREP
 EGREP
@@ -3474,10 +3479,30 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 
+
+if true; then
+  HAVE_WEB100_TRUE=
+  HAVE_WEB100_FALSE='#'
+else
+  HAVE_WEB100_TRUE='#'
+  HAVE_WEB100_FALSE=
+fi
+
+
 else
 
                LINKED_WEB100LIB=""
                INCLUDED_WEB100LIB=""
+
+
+if false; then
+  HAVE_WEB100_TRUE=
+  HAVE_WEB100_FALSE='#'
+else
+  HAVE_WEB100_TRUE='#'
+  HAVE_WEB100_FALSE=
+fi
+
 
 fi
 
@@ -3583,11 +3608,8 @@ NDTINCS='-I$(NDTINCDIR)'
 # Java config files
 #
 GCJ=javac
-# NDTGCJFLAGS="-source 1.3"
-# GCJFLAGS="-source 1.3"
 NDTGCJFLAGS="-source 1.4"
 GCJFLAGS="-source 1.4"
-
 
 
 
@@ -4545,6 +4567,58 @@ fi
 
 
 
+for ac_prog in javac
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_SGCJ+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$SGCJ"; then
+  ac_cv_prog_SGCJ="$SGCJ" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_SGCJ="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+fi
+fi
+SGCJ=$ac_cv_prog_SGCJ
+if test -n "$SGCJ"; then
+  { echo "$as_me:$LINENO: result: $SGCJ" >&5
+echo "${ECHO_T}$SGCJ" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+  test -n "$SGCJ" && break
+done
+
+
+
+if test -n "$SGCJ"; then
+  HAVE_GCJ_TRUE=
+  HAVE_GCJ_FALSE='#'
+else
+  HAVE_GCJ_TRUE='#'
+  HAVE_GCJ_FALSE=
+fi
+
 
 # Checks for libraries.
 
@@ -5264,7 +5338,8 @@ done
 
 
 
-for ac_header in arpa/inet.h fcntl.h netdb.h netinet/in.h stdlib.h string.h sys/socket.h sys/time.h unistd.h linux/sockios.h net/ethernet.h netinet/ip6.h
+
+for ac_header in arpa/inet.h fcntl.h netdb.h netinet/in.h stdlib.h string.h sys/socket.h sys/time.h unistd.h linux/sockios.h net/ethernet.h netinet/ip6.h linux/icmpv6.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
@@ -7031,6 +7106,20 @@ echo "$as_me: error: conditional \"am__fastdepCC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${HAVE_WEB100_TRUE}" && test -z "${HAVE_WEB100_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_WEB100\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_WEB100\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_WEB100_TRUE}" && test -z "${HAVE_WEB100_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_WEB100\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_WEB100\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${am__fastdepCC_TRUE}" && test -z "${am__fastdepCC_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"am__fastdepCC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -7042,6 +7131,13 @@ if test -z "${am__fastdepGCJ_TRUE}" && test -z "${am__fastdepGCJ_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"am__fastdepGCJ\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"am__fastdepGCJ\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_GCJ_TRUE}" && test -z "${HAVE_GCJ_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_GCJ\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_GCJ\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -7661,6 +7757,8 @@ AMDEPBACKSLASH!$AMDEPBACKSLASH$ac_delim
 CCDEPMODE!$CCDEPMODE$ac_delim
 am__fastdepCC_TRUE!$am__fastdepCC_TRUE$ac_delim
 am__fastdepCC_FALSE!$am__fastdepCC_FALSE$ac_delim
+HAVE_WEB100_TRUE!$HAVE_WEB100_TRUE$ac_delim
+HAVE_WEB100_FALSE!$HAVE_WEB100_FALSE$ac_delim
 LINKED_WEB100LIB!$LINKED_WEB100LIB$ac_delim
 INCLUDED_WEB100LIB!$INCLUDED_WEB100LIB$ac_delim
 LINKED_PCAPLIB!$LINKED_PCAPLIB$ac_delim
@@ -7671,13 +7769,11 @@ NDTLIBS!$NDTLIBS$ac_delim
 NDTLIBDIR!$NDTLIBDIR$ac_delim
 NDTINCDIR!$NDTINCDIR$ac_delim
 TOP_BUILD_DIRS!$TOP_BUILD_DIRS$ac_delim
-GCJ!$GCJ$ac_delim
 NDTGCJFLAGS!$NDTGCJFLAGS$ac_delim
 NDTJAR!$NDTJAR$ac_delim
 NDTJARFLAG!$NDTJARFLAG$ac_delim
+GCJ!$GCJ$ac_delim
 GCJFLAGS!$GCJFLAGS$ac_delim
-GCJDEPMODE!$GCJDEPMODE$ac_delim
-am__fastdepGCJ_TRUE!$am__fastdepGCJ_TRUE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -7719,7 +7815,12 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+GCJDEPMODE!$GCJDEPMODE$ac_delim
+am__fastdepGCJ_TRUE!$am__fastdepGCJ_TRUE$ac_delim
 am__fastdepGCJ_FALSE!$am__fastdepGCJ_FALSE$ac_delim
+SGCJ!$SGCJ$ac_delim
+HAVE_GCJ_TRUE!$HAVE_GCJ_TRUE$ac_delim
+HAVE_GCJ_FALSE!$HAVE_GCJ_FALSE$ac_delim
 CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
@@ -7728,7 +7829,7 @@ ac_aux_dir!$ac_aux_dir$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 7; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 12; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
